

# This file was *autogenerated* from the file src/02_principal_part_demo.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_30000 = Integer(30000); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0 = Integer(0); _sage_const_1e4 = RealNumber('1e4')#!/usr/bin/env sage
# Purpose: principal-part match on S via t_X(s); compare with log L(E,s) at s=1+eps.
# Usage:   sage src/02_principal_part_demo.sage <curve> [eps=1e-3] [B=30000] [eta=1.2]
# Prints:  t_X(1+eps), r*log(1 - t_X), log L(E,1+eps), slope checks vs rank.
# Output:  data/principal_part_*.json with all computed values
# Tip:     increase B or X inside the code to reduce variance; eta controls C^1 window tail.

import sys
from sage.all import *

# Import save utils
sys.path.append('src')
from save_utils import save_json_results

curve = sys.argv[_sage_const_1 ] if len(sys.argv) > _sage_const_1  else '37a1'
eps = RealNumber(sys.argv[_sage_const_2 ]) if len(sys.argv) > _sage_const_2  else RealNumber('1e-3')
B = Integer(sys.argv[_sage_const_3 ]) if len(sys.argv) > _sage_const_3  else _sage_const_30000 
eta = RealNumber(sys.argv[_sage_const_4 ]) if len(sys.argv) > _sage_const_4  else RealNumber('1.2')

E = EllipticCurve(curve)
N = E.conductor()
C = ComplexField(_sage_const_100 )

def frob_eigs(a, l):
    D = C(a*a - _sage_const_4 *l)
    sD = D.sqrt()
    return ( (a + sD)/_sage_const_2 , (a - sD)/_sage_const_2  )

def window(t, eta=_sage_const_1p2 ):
    if t <= _sage_const_1 : return _sage_const_1 
    if t >= _sage_const_1 +eta: return _sage_const_0 
    r = (t-_sage_const_1 )/eta
    return _sage_const_1  - (_sage_const_3 *r**_sage_const_2  - _sage_const_2 *r**_sage_const_3 )

def t_X(E, X, s, B=_sage_const_30000 , eta=_sage_const_1p2 ):
    N = E.conductor()
    S = C(_sage_const_0 )
    # Store individual terms for analysis
    terms = []
    for l in prime_range(min(B, ceil((_sage_const_1 +eta)*X))):
        if N % l == _sage_const_0 :
            continue
        a = E.ap(l)
        alpha, beta = frob_eigs(a, l)
        m = _sage_const_1 
        while l**m <= (_sage_const_1 +eta)*X:
            wt = window(l**m / X, eta)
            if wt != _sage_const_0 :
                term_val = C(wt) * (alpha**m + beta**m) / (m * (l**(m*s)))
                S += term_val
                terms.append({
                    'l': int(l),
                    'm': int(m),
                    'window_weight': float(wt),
                    'term_value': {'real': float(term_val.real()), 'imag': float(term_val.imag())}
                })
            m += _sage_const_1 
    return S, terms

X = RealNumber(_sage_const_1e4 )
s1 = RealNumber(_sage_const_1 ) + eps
r = E.rank()

# log det_fin(I - A_X(s)) on S where A_X(s) = t_X(s) * I_S
val_t, t_X_terms = t_X(E, X, s1, B=B, eta=eta)
logdet_fin = r * log(_sage_const_1  - val_t)

# Compare with log L(E,s) via Sage's L-series (numeric)
L = E.lseries().dokchitser()
Lval = C(L(s1))
logL = log(Lval)

print(f"[02] Curve {curve}, r={r}, X={X}, eps={eps}")
print(f"     t_X(1+eps) = {val_t}")
print(f"     log det_fin(I - A_X(1+eps)) = {logdet_fin}")
print(f"     log L(E,1+eps) = {logL}")

# Slope checks for rank verification
slope_checks = []
for h in [eps, eps/_sage_const_2 , eps/_sage_const_4 ]:
    s = _sage_const_1  + h
    Lh = C(L(s))
    slope = (log(abs(Lh))/log(h)).real()
    print(f"     slope check h={h} : log|L(1+h)|/log(h) ≈ {slope}")
    slope_checks.append({
        'h': float(h),
        'L_value': {'real': float(Lh.real()), 'imag': float(Lh.imag())},
        'slope': float(slope)
    })

# Save all results to JSON
results = {
    'curve': curve,
    'parameters': {
        'X': float(X),
        'eps': float(eps),
        'B': int(B),
        'eta': float(eta)
    },
    'curve_data': {
        'conductor': int(N),
        'rank': int(r)
    },
    'results': {
        't_X_value': {'real': float(val_t.real()), 'imag': float(val_t.imag())},
        'log_det_fin': {'real': float(logdet_fin.real()), 'imag': float(logdet_fin.imag())},
        'log_L': {'real': float(logL.real()), 'imag': float(logL.imag())},
        'L_value': {'real': float(Lval.real()), 'imag': float(Lval.imag())}
    },
    'slope_checks': slope_checks,
    't_X_terms': t_X_terms[:_sage_const_100 ]  # Save first 100 terms to avoid huge files
}

filename = save_json_results('principal_part', results, curve)
print(f"[02] Saved results to {filename}")

